---
title             : "Network analysis of traffic behaviors"
shorttitle        : "Title"

author: 
  - name          : "Markus Mattsson"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "P.O. Box 9, Siltavuorenpenger 1 A, FI-00014 University of Helsinki, Finland"
    email         : "markus.mattsson@helsinki.fi"
  - name          : "Markus Mattsson"
    affiliation   : "1"

affiliation:
  - id            : "1"
    institution   : "University of Helsinki"
  
author_note: |
  Traffic Research Unit
  University of Helsinki

abstract: |
  Self-report-based research on traffic behavior is most often carried out with the instrumental goal of predicting     traffic accidents in mind, rather than out of inherent interest in how people behave, think or feel in traffic.    Therefore, nomological relationships of traffic behaviors and accidents are of central importance to the researcher. The most commonly used analysis method of self-report data is factor analysis, followed by the calculation of unit-weighted average scores of the frequencies of the behaviors that load on the factors. However, recent research (Mattsson 2012, Mattsson et al., 2015) has shown that the factor models of the commonly-used Driver Behavior Questionnaire lack the property of measurement equivalence across subgroups of respondents. This has the unfortunate consequence of rendering the meanings of the average scores group-specific. On the other hand, this may not as big a problem as it first seems, as the average scores are not relevant for the nomological relationships, which are quantified using some measure of association (such as a correlation coefficient or another). In this contribution I pursue the idea of modelling drivers’ self-reported behaviors, thoughts and self-perceptions as an interrelated nomological network rather than as reflections of in principle unobservable latent variables, and suggest that the previously noted lack of measurement equivalence reflects the fact that postulating latent variables as an additional level of abstraction is unnecessary in self-report-based traffic research. Further, I examine the pairwise associations between nodes of the nomological network and being involved in a traffic accident. 
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

figsintext        : no
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : yes

lang              : "english"
class             : "man"
output            : papaja::apa6_pdf
---

```{r load_packages, include = FALSE}
library("papaja")
```

```{r analysis_preferences}
# Seed for random number generation
set.seed(42)
```



# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
